services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${BOOK_API_DB_NAME}'
      - 'POSTGRES_PASSWORD=${BOOK_API_DB_PASSWORD}'
      - 'POSTGRES_USER=${BOOK_API_DB_USER}'
    ports:
      - '${BOOK_API_DB_PORT}:5432'
