spring.application.name=book-api

spring.datasource.url=jdbc:postgresql://${BOOK_API_DB_HOST}:${BOOK_API_DB_PORT}/${BOOK_API_DB_NAME}
spring.datasource.username=${BOOK_API_DB_USER}
spring.datasource.password=${BOOK_API_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
